export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const GET_REPO_INFO = 'GET_REPO_INFO';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const GET_STORED_DATA = 'GET_STORED_DATA';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';